---
driver:
  name: vagrant
  gui: false
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    driver:
      box: foxguard/centos73

suites:
  - name: default
    run_list:
      - recipe[fgs_docker::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      fgs_docker:
        enable-non-sudo-access: true
